#!/bin/bash
######################################################
## Author   : zhaowenyu
## Mail     : admin@zhaowenyu.com
## Version  : v1.0
## Date     : 2017-09-27
## Descript : tengine mananger script
## Charset  : set encoding=utf8 
######################################################

nginxd=/usr/local/tengine/sbin/nginx
nginx_config=/usr/local/tengine/conf/nginx.conf
action=$1

start() {
    ps auxf|grep nginx|grep -v grep  && echo "nginx已经在运行了" && exit 0
    $nginxd -c $nginx_config &>/dev/null && echo "start成功" || echo "start失败"
}

stop() {
    $nginxd -s stop &>/dev/null && echo "stop成功" || echo "stop失败"
}

reload() {
    $nginxd -s reload &>/dev/null && echo "reload成功" || echo "reload失败"
}

status() {
    ps auxf|grep nginx|grep -v grep || echo "tengine没有运行"
}

main() {
    case "$action" in
    start)
            start
            ;;
    stop)
            stop
            ;;
    reload)
            reload
            ;;
    restart)
            stop
            start
            ;;
    status)
            status 
            ;;
    *)
            echo "Usage: tengine {start|stop|restart|reload|status|help}"
            exit 1
    esac
}

main
