#!/bin/bash
######################################################
## Author   : zhaowenyu
## Mail     : admin@zhaowenyu.com
## Version  : v1.0
## Date     : 2017-09-27 create
## update.  : 2021-12-13 support run already running nginxd host
## Descript : tengine mananger script
## Charset  : set encoding=utf8 
######################################################

nginxd=/usr/local/tengine/sbin/nginx
nginx_config=/usr/local/tengine/conf/nginx.conf
nginx_pid=/usr/local/tengine/logs/nginx.pid

action=$1

start() {
    if [ -f $nginx_pid ];then
        echo "    nginx已经在运行了: $nginx_pid" 
        ps auxf |grep -v grep|grep $nginxd
        exit 0
    fi
    $nginxd -c $nginx_config &>/dev/null && echo "    start成功" || echo "    start失败"
}

stop() {
    $nginxd -s stop &>/dev/null && echo "    stop成功" || echo "    stop失败,"
}

reload() {
    $nginxd -s reload &>/dev/null && echo "    reload成功" || echo "    reload失败"
}

status() {
    ps auxf|grep $nginxd|grep -v grep || echo "    tengine没有运行"
}

main() {
    case "$action" in
    start)
            start
            ;;
    stop)
            stop
            ;;
    reload)
            reload
            ;;
    restart)
            stop
            start
            ;;
    status)
            status 
            ;;
    *)
            echo ""
            echo "    Usage: $0 {start|stop|restart|reload|status|help}"
            echo ""
            exit 1
    esac
}

main
